### ISSUE TITLE
License Apache/MIT

### ISSUE THREAD

**Issue by UXDart** [andybotting/oystermate#12]
Hello! could you add a license to this repo? like Apache or MIT? 
I would like to rewrite part of this code to another language but there is no license.. :(

TIA

**Comment by andybotting** [comment]
You're right I did forget the license. 

My apps are all GPL, but I'm happy for to you to use the concepts in another language if you like. Can you tell me more about what your plans are?

**Comment by UXDart** [comment]
I want to show the balance of oyster cards in an iphone app (objective-c) that shows the shortest path between stops (Tube). can you please add an Apache or MIT license?
Thanks!

**Comment by andybotting** [comment]
No, I'd prefer GPLv3, but I'm happy to grant you access to use the code for your iPhone app.

**Comment by UXDart** [comment]
Thanks! I understand you don't want to put the full android app in that license, but what about creating another repo (maybe calling parser) with just the Provider folder files and make it MIT? if you can't I understand, really! I will search for another option or create my own parser as I can't legally use it if that is not the case. thank you!

**Comment by andybotting** [comment]
As the owner of this code, I grant you access to use it any project you like. Go nuts.

**Comment by andybotting** [comment]
You can use it under your own MIT/Apache project without any restrictions.

**Comment by UXDart** [comment]
Thank you :) but these posts have no legal value... I can't use it. thanks anyway!

**Comment by UXDart** [comment]
I just implemented it, and then I checked your code, I think you need to change it... now there is a list of oyster cards directly and you need to check for urls starting with "https://oyster.tfl.gov.uk/oyster/selectCard.do?..."

HTH
