### ISSUE TITLE
Doesn't recognize multiple cards

### ISSUE THREAD

**Issue by jimlambe** [andybotting/oystermate#6]
When I use the app it doesn't recognize the fact that I have 2 Oyster cards in fact it shows card number as null. The ability to see multiple card balances would be great ... Jim!

**Comment by andybotting** [comment]
Hi Jim,

I had a report from another user this morning about the same issue.
I'm currently working on it, and I hope to have a new release within a
week.

cheers,

Andy

On Sun, Jun 26, 2011 at 6:09 PM, jimlambe
reply@reply.github.com
wrote:

**Comment by jimlambe** [comment]
Great, let me know when you need someone to test it .... Jim!

**Comment by andybotting** [comment]
Hi Jim,

I have a build that is working now with multiple cards.

I'm just doing some code cleanup and UI stuff, but I should have a test build for you sometime over the weekend or early next week.

cheers

**Comment by andybotting** [comment]
Hi Jim,

I've got a test build with multiple card support, if you'd like to try it out.

https://github.com/downloads/andybotting/oystermate/OysterMate-0.2-rc1.apk

Let me know if you need any help to install it.

cheers

**Comment by jimlambe** [comment]
Excellent, will let you know how I get on

..... Jim!

On 10/07/11 10:08, andybotting 
reply+i-1117587-f2a761ae98ca51a2c0f6f933b0960ea0dab6112d-at-reply.github.com 
|github/Example Allow| wrote:

> Hi Jim,
> 
> I've got a test build with multiple card support, if you'd like to try it out.
> 
> https://github.com/downloads/andybotting/oystermate/OysterMate-0.2-rc1.apk
> 
> Let me know if you need any help to install it.
> 
> cheers

**Comment by jimlambe** [comment]
Andy, it is recognizing both my Oyster cards and updating with the 
correct info. Initially when I clicked on the buttons (can't see the 
writing on buttons) next to to the amounts it always went  to 
https://oyster.tfl.gov.uknull but then fixed itself and now goes to the 
add credit/auto top up pages of oyster.tfl.gov.uk. The only thing I did 
to the phone was to try changing the theme to see if the writing on the 
buttons would appear, they didn't.

..... Jim!

On 10/07/11 10:08, andybotting 
reply+i-1117587-f2a761ae98ca51a2c0f6f933b0960ea0dab6112d-at-reply.github.com 
|github/Example Allow| wrote:

> Hi Jim,
> 
> I've got a test build with multiple card support, if you'd like to try it out.
> 
> https://github.com/downloads/andybotting/oystermate/OysterMate-0.2-rc1.apk
> 
> Let me know if you need any help to install it.
> 
> cheers

**Comment by andybotting** [comment]
Hi Jim,

If you can reproduce it, I would appreciate if you can install 'log collector' from the Android Market and run it just after Oyster Mate does its thing. Then use log collector to email the log to andy@andybotting.com and I should be able to get a better idea about what's going on.

Also, what is the phone you're running it on? What version of Android does it have?

Thanks!
