### ISSUE TITLE
Force Closes as of 14/09/11

### ISSUE THREAD

**Issue by gkainth** [andybotting/oystermate#7]
Running Cyanogen 7 on an LG Optimus 2x.

error report submitted, 
Nullpointerexception, - AccountInfo.java line 56, method - hasOysterCard

**Comment by andybotting** [comment]
Hi,

There's an edge case where some accounts cause oystermate to crash. If I
send you a test build, would you be willing to test and send me some logs?

Cheers,

Andy
On Sep 14, 2011 11:47 PM, "gkainth" <
reply@reply.github.com>
wrote:

**Comment by gkainth** [comment]
sure, no prob.

**Comment by andybotting** [comment]
Great. I'll put one together with some instructions in the next day or so.

Cheers
On Sep 15, 2011 11:42 AM, "gkainth" <
reply@reply.github.com>
wrote:

**Comment by andybotting** [comment]
Hi gkainth,

I've created a test build here:
https://github.com/downloads/andybotting/oystermate/OysterMate-0.3.1-debug.apk

Once you install it, also install 'Log Collector' from the Android Market. Open OysterMate up again, and right after it crashes, go into Log Collector and tell it to email the log to tubechaser@andybotting.com.

From there, I should be able to get a good idea about why it's crashing.

Thanks

**Comment by andybotting** [comment]
No response, and a new version out. Closing this ticket.
